src/main/java/edu/upc/dsbw/spring/business/model/Author.java
package edu.upc.dsbw.spring.business.model;

import java.util.LinkedList;
import java.util.List;

public class Author {

	private String firstName;
	private String lastName;
	private List<Book> books = new LinkedList<Book>(); 
	
	public Author(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Book newBook(String title, int publicationYear) {
		Book result = new Book(this, title, publicationYear);
		books.add(result);
		return result;
	}
	
	void removeBook(Book book) {
		this.books.remove(book);
	}

	void addBook(Book book) {
		this.books.remove(book);
	}

	public String getName(){
		return firstName + " " + lastName;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}
	
	public List<Book> getBooks() {
		return books;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result
				+ ((lastName == null) ? 0 : lastName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Author other = (Author) obj;
		if (firstName == null) {
			if (other.firstName != null)
				return false;
		} else if (!firstName.equals(other.firstName))
			return false;
		if (lastName == null) {
			if (other.lastName != null)
				return false;
		} else if (!lastName.equals(other.lastName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return getName();
	}

}

src/main/java/edu/upc/dsbw/spring/business/model/Book.java
package edu.upc.dsbw.spring.business.model;


public class Book {

	private Long id;
	private Author author;
	private String title;
	private int publicationYear;

	Book(Author author, String title, int publicationDate) {
		this.author = author;
		this.title = title;
		this.publicationYear = publicationDate;
	}

	public void remove() {
		author.removeBook(this);
	}

	public void update(Author author, String title, int publicationDate) {
		if(!this.author.equals(author)){
			this.author.removeBook(this);
			this.author = author;
			author.addBook(this);
		}
		this.title = title;
		this.publicationYear = publicationDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(long id) {
		if(this.id!=null && this.id != id){
			throw new IllegalStateException();
		}
		this.id = id;
		
	}

	public String getTitle() {
		return title;
	}

	public Author getAuthor() {
		return author;
	}

	public int getPublicationYear() {
		return publicationYear;
	}

}

src/main/java/edu/upc/dsbw/spring/business/BooksController.java
package edu.upc.dsbw.spring.business;

import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import edu.upc.dsbw.spring.business.model.Author;
import edu.upc.dsbw.spring.business.model.Book;

public class BooksController {

	private long nextBookId = 0;
	private long nextAuthorId = 0;
	private Map<Long, Book> booksDB = new HashMap<Long, Book>();
	private Map<Long, Author> authorsDB = new HashMap<Long, Author>();

	public enum ListBooksOrderBy {
		insertionDate, title, author, publicationYear
	}

	public List<Book> listBooks(final ListBooksOrderBy orderBy) {
		List<Book> books = new LinkedList<Book>(booksDB.values());
		if (orderBy != ListBooksOrderBy.insertionDate) {
			Collections.sort(books, new Comparator<Book>() {

				public int compare(Book b1, Book b2) {
					switch (orderBy) {
					case title:
						return b1.getTitle().compareTo(b2.getTitle());
					case author:
						return b1.getAuthor().getName()
								.compareTo(b2.getAuthor().getName());
					case publicationYear:
						return b2.getPublicationYear() - b1.getPublicationYear();
					default:
						throw new IllegalArgumentException(
								"Unknown order by criteria " + orderBy);
					}
				}
			});
		}
		return books;
	}

	public Book getBook(Long id) {
		return booksDB.get(id);
	}

	public void addBook(Long authorId, String title, int publicationYear) {
		Author author = getAuthor(authorId);
		if (author == null)
			throw new IllegalArgumentException("Unknown author " + authorId);
		Book result = author.newBook(title, publicationYear);
		result.setId(nextBookId++);
		booksDB.put(result.getId(), result);
	}

	public void removeBook(Long id) {
		Book book = getBook(id);
		book.remove();
		booksDB.remove(book);
	}

	public void updateBook(Long id, Long authorId, String title,
			int publicationYear) {
		Book book = getBook(id);
		if (book == null)
			throw new IllegalArgumentException("Unknown book " + id);
		Author author = getAuthor(authorId);
		if (author == null)
			throw new IllegalArgumentException("Unknown author " + authorId);
		book.update(author, title, publicationYear);
	}

	public List<Author> listAuthors() {
		List<Author> authors = new LinkedList<Author>(authorsDB.values());
		Collections.sort(authors, new Comparator<Author>() {

			public int compare(Author a1, Author a2) {
				return a1.getName().compareTo(a2.getName());
			}
		});
		return authors;
	}

	public Author getAuthor(Long id) {
		return authorsDB.get(id);
	}

	public long addAuthor(String firstName, String lastName) {
		long id = nextAuthorId++;
		authorsDB.put(id, new Author(firstName, lastName));
		return id;
	}
	
	public void removeAuthor(Long id){
		Author author = getAuthor(id);
		if (author == null)
			throw new IllegalArgumentException("Unknown author " + id);
		for(Book b : author.getBooks()){
			booksDB.remove(b.getId());
		}
	}

}

src/main/java/edu/upc/dsbw/spring/web/BooksController.java
package edu.upc.dsbw.spring.web;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import edu.upc.dsbw.spring.business.BooksController.ListBooksOrderBy;
import edu.upc.dsbw.spring.business.model.Book;

@Controller
@RequestMapping("/books/*")
public class BooksController {
	
	@Autowired edu.upc.dsbw.spring.business.BooksController domainController;

	@RequestMapping(value="/by/{orderBy}",method=RequestMethod.GET)
	public ModelAndView listBooks(@PathVariable("orderBy") ListBooksOrderBy orderBy){
		List<Book> books = domainController.listBooks(orderBy);
		return new ModelAndView("books/list","books",books);
	}
	
	@RequestMapping(value="/{id}",method=RequestMethod.GET)
	public ModelAndView getBook(@PathVariable("id") Long id){
		Book book = domainController.getBook(id);
		return new ModelAndView("books/detail","book",book);
	}
	
	@RequestMapping(value="/{id}",method=RequestMethod.POST)
	public ModelAndView editBook(@PathVariable("id") Long id, @RequestParam("authorId") Long authorId, @RequestParam("title") String title, @RequestParam("publicationYear") int publicationYear){
		domainController.updateBook(id, authorId, title, publicationYear);
		return new ModelAndView("redirect:"+id);
	}
	
	
}

src/main/webapp/WEB-INF/jsp/books/detail.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Books list</title>
</head>
<body>
	<h1>Book</h1>
	<label>Author: </label><p><c:out value="${book.author.name}"/></p>
	<label>Title: </label><p><c:out value="${book.title}"/></p>
	<label>Publication year: </label><p><c:out value="${book.publicationYear}"/></p>
</body>
</html>

src/main/webapp/WEB-INF/jsp/books/list.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Books list</title>
</head>
<body>
	<h1>Books</h1>
	<table>
		<thead>
			<tr><th>Author</th><th>Title</th><th>Publication</th><th></th></tr>
		</thead>
		<tbody>
			<c:forEach items="${books}" var="book">
				<tr>
				<td><c:out value="${book.author.name}"/></td>				
				<td><c:out value="${book.title}"/></td>				
				<td><c:out value="${book.publicationYear}"/></td>
				<td>
					<a href="<c:out value="/spring/books/${book.id}.html"/>">Detail</a>
				</td>
				</tr>				
			</c:forEach>
		</tbody>
	</table>
</body>
</html>

src/main/webapp/index.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<html>
  <head><title>Example :: Spring Application</title></head>
  <body>
    <h1>Example - Spring Application</h1>
    <p>This is my test.</p>
  </body>
</html>